### ISSUE TITLE
Información de instalación

### ISSUE THREAD

**Issue by josecarpio** [Mibew/mibew#108]
El dia de hoy instale la beta de mibew-2.0.0-beta.2 , al configurar y instalar la versión. todo excelente hasta que me conecte pero  a la hora de que los usuarios iban hablar con el operador. No llegaba la información de que un Usuario que quería hablar con un operador. No aparecía en la "Lista de visitante en Espera " intente varias veces. y hasta el momento me aparece nada en la "Lista de visitante en Espera ".

**Comment by faf** [comment]
And why do you think that we speak Spanish?

**Comment by faf** [comment]
Issues should be written in English and should contain all necessary information.
