### ISSUE TITLE
Instant text view (Writing visualisation)

### ISSUE THREAD

**Issue by cjmaxik** [Mibew/mibew#113]
Feature request - see what visitor writes in real time, this thing help operators with fast answers.

Реквест - видеть то, что пишет посетитель, в режиме реального времени, чтобы оператор мог найти ответ намного быстрее.

**Comment by JustBlackBird** [comment]
We could think about it, but one should understand that there are many tasks with higher priority right now.

By the way, pull requests are welcome.

**Comment by JustBlackBird** [comment]
Also I guess that such feature can be implemented as a standalone plugin. If so, there is no need to pull the feature into the core.

**Comment by cjmaxik** [comment]
In my opinion, this feature should be a core feature.

**Comment by faf** [comment]
@cjmaxik does your opinion based upon something more weighty than your personal confidence?

the whole idea of the core and the plugins is that the core should encapsulate only crucial low-level systems and major basic functions. everything else should be implemented as plugins. is there a good reason to treat the feature you're talking about as a major basic function?

**Comment by dmcdaniel12** [comment]
I agree that this should be a plugin and not a core feature. Why add more overhead into the product? It's not needed, but would make a good addon feature.

**Comment by JustBlackBird** [comment]
This should not be implemented in the core thus I'm closing the issue. Hope someone could create a plugin for it :wink:
