### ISSUE TITLE
True\Punycode

### ISSUE THREAD

**Issue by cjmaxik** [Mibew/mibew#118]
Hello!
In 2.0.0-beta.4 True\Punycode is missed.

After saving settings:
Fatal error: Class 'True\Punycode' not found in /home/c5338/public_html/ets2mp/mibew/libs/classes/Mibew/Mail/Utils.php on line 130

**Comment by moswaldosf** [comment]
Indeed I have the Same inconvenience When Trying to Install Application ...

**Comment by faf** [comment]
Fixed in 2.0.0-beta.5 released just a moment ago. :)
