### ISSUE TITLE
Allow setting client name via URL GET parameter. Allow SSO authentication for clients (not operators).

### ISSUE THREAD

**Issue by mescon** [Mibew/mibew#119]
Having to ask clients what their names are gives them a lot of trust.
We use Mibew as a means of support for logged in users (with different pricing for each customer).

A user can pretend to be from Company A and ask "Whats the price of this?" and get a reply - but in reality, the user is from Company B and has just been given prices from a competitors pricing sheet.

In Mibew 1.6.x I set some sort of "manual verification" by setting the URL to client.php?info=$username and then tell operators to always check what the "Info" says.

**Comment by JustBlackBird** [comment]
In Mibew 2.0 you can still send the `info` GET param to `<mibew base URL>/chat` to provide extra info about the user.

Also, I believe you can create a custom plugin for Mibew 2.0 which will provide real user name and any other metadata to operator. This plugin could use any authorization logic you want to.
