### ISSUE TITLE
Embed Chatwindow in SSL-Site

### ISSUE THREAD

**Issue by MDXDave** [Mibew/mibew#120]
If you are using the mibew system on a ssl based site, the file https://example.com/cht/style/popup/default returns 
> /**/Mibew.Utils.loadStyleSheet("__http__:\/\/example.com\/styles\/chats\/default\/iframe.css");

But should return
> /**/Mibew.Utils.loadStyleSheet("__https__:\/\/example.com\/styles\/chats\/default\/iframe.css");

Simple fix:
/libs/classes/Mibew/Controller/Chat/StyleController.php line 55:
>             $response->setData(str_replace("http","https",$css))

**Comment by JustBlackBird** [comment]
I cannot reproduce the problem. It seems it is your local issue.

Are you sure you're requesting https://example.com/chat/style/popup/default using HTTPS? The output actually depends on what protocol is using for request.

Also, if you use nginx make sure apache gets HTTPS responses and not HTTP.

**Comment by MDXDave** [comment]
Sorry, my fault, i use cloudflare, but forward to non-ssl site. My visitors see https, but the internal redirect from cloudflare to site uses only http

**Comment by JustBlackBird** [comment]
Mibew knows nothing about any kind of proxy you are using and it was done intentionally. It's not a job of a web application to guess is there any proxies in front of it or not.

If you want to use a proxy you have to configure requests forwarding correctly. Also any HTTP headers starting with `X-` are non-standard, so I don't think we should check `HTTP_X_FORWARDED_PROTO` inside Mibew.
