### ISSUE TITLE
Проблемы с URL'ами

### ISSUE THREAD

**Issue by stdex** [Mibew/mibew#124]
>Apache/2.4.7 (Ubuntu)
>PHP 5.5.9-1ubuntu4.9 (cli)
>Mysql 5.5.43-0ubuntu0.14.04.1 (Ubuntu)
>nginx/1.4.6 (Ubuntu)
>mod_rewrite
>GD 2.1.1-dev

Апач стоит на 8080 порту, nginx выступает в качестве прокси сервера, проксирует 8080 на 80.
1) При попытке зайти по URL: http://localhost/mibew/ происходит редирект на: http://localhost/mibew/operator - страница выдает 404
Страница http://localhost/mibew/index.php/operator открывается нормально.
2) Тоже самое и с другими URL, например http://localhost/mibew/operator/button-code выдает 404, а http://localhost/mibew/index.php/operator/button-code открывается.

**Comment by JustBlackBird** [comment]
First of all Mibew is an international project, so it's better to use English for issues. If you don't speak English use the Russian support board at our forum.

Next, it's seems that nginx configuration you use is wrong. All requests to Mibew (excluding existing static files) should be processed with `index.php`. For details, check Apache's `mod_rewrite` directive that are used in Mibew: https://github.com/Mibew/mibew/blob/master/src/mibew/.htaccess#L30-#L46

**Comment by JustBlackBird** [comment]
Here is a part of nginx config that could help you: https://mibew.org/forums/index.php/topic,191725.msg198602.html#msg198602 (though I cannot guarantee it works fine).
