### ISSUE TITLE
Operator permission

### ISSUE THREAD

**Issue by ceylani** [Mibew/mibew#132]
when checked the "View another operator's chat thread" option in the admin console -> operator -> permissions, getting an SQL error in the operator panel -> Chat history -> everywhere.

**Comment by JustBlackBird** [comment]
What version of Mibew are you talking about? And what kind of SQL error do you receive?

**Comment by JustBlackBird** [comment]
Cannot reproduce on Mibew 2.1.0

**Comment by ceylani** [comment]
mibew 2.1.0

**Comment by JustBlackBird** [comment]
Once again, what kind of SQL error do you receive?

**Comment by ceylani** [comment]
Query failed: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') OR thread.groupid IN ('1'))' at line 1

**Comment by ceylani** [comment]
I have two groups and there is an operator in each group.

**Comment by JustBlackBird** [comment]
Now I can confirm that it's a bug. The fix will be done soon.
