### ISSUE TITLE
Minimize iFrame/Window

### ISSUE THREAD

**Issue by kckunal2612** [Mibew/mibew#133]
I have customized my mibew iframe in a way that the chat window occupies only a portion of the screen and slides up from the bottom right of the screen when the CHAT button is clicked. I have put the slide command in ```Mibew.ChatPopup.IFrame.prototype.open()``` function as shown below -
```
Mibew.ChatPopup.IFrame.prototype.open() = func() {
....
 //now that the iframe has been created, display it after sliding it from bottom
        $(".mibew-chat-frame").show('slide', { direction: 'down' }, 1000);
        this.iframe.style.display = 'block';
        this.iframe.src = url || this.buildChatUrl();
...
```
Also, I added a minimize button at the top right corner of the mibew chat frame so that users can slide it down (just like we used to see in GTalk Chat Window).  I added the minimize button in the ```#logo-region``` and added an **event** in ```../layouts/chat.js```.
However, I am at a loss at implementing the minimize functionality. Could you please put a new CONTROL button for minimizing the chat window in the next build ? Or help me with this issue here ? Thanks.

**Comment by CarlaTeo** [comment]
@kckunal2612  Were you able to do it? 
I am also interested in a minimizing functionality.
