### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by sergeyl777** [Mibew/mibew#134]
version script: mibew-2.1.0
System: php 5.4 mysql 5
Path: mibew/install.php
Fatal error: require(): Failed opening required 'mibew/vendor/composer/ClassLoader.php' (include_path='.:/usr/local/php54/lib/php') in mibew/vendor/composer/autoload_real.php on line 12

**Comment by JustBlackBird** [comment]
Does file `mibew/vendor/composer/autoload_real.php` actually exist?

**Comment by sergeyl777** [comment]
File the ClassLoader exist. All files mibew 2.1.0 exist

**Comment by JustBlackBird** [comment]
Cannot reproduce the problem. Sorry.

If `mibew/vendor/composer/ClassLoader.php` file exits then something is wrong with file permissions on your server.

**Comment by kyrtgod** [comment]
check the names of all the files.

example:
/vendor/composer/ClassLoader.php   - OK
/vendor/composer/classloader.php     - NO

**Comment by JustBlackBird** [comment]
Closed due to inactivity. If the problem persists, let me know and I'll reopen the issue.
