### ISSUE TITLE
Error install mibew 2.1.0

### ISSUE THREAD

**Issue by sergeyl777** [Mibew/mibew#135]
System: unix, msql5, php 5.4
Script: mibew 2.1.0
Error: Warning: require(mibew/vendor/composer/ClassLoader.php): failed to open stream: No such file or directory in mibew/vendor/composer/autoload_real.php on line 12

Fatal error: require(): Failed opening required 'mibew/vendor/composer/ClassLoader.php' (include_path='.:/usr/local/php54/lib/php') in mibew/vendor/composer/autoload_real.php on line 12

Possible: classloader.php and ClassLoader.php - capital letters on unix system.
How to solve the problem???? This is problem was in the mibew-1615.

**Comment by JustBlackBird** [comment]
This is a clone of #134.

**Comment by JustBlackBird** [comment]
@sergeyl777 list all additional info at #134.
