### ISSUE TITLE
Group description don't change when group change when client start a new chat

### ISSUE THREAD

**Issue by wanderlp** [Mibew/mibew#138]
Group description don't change when group changes in new chat window.

I mean in http://<server>/mibew/index.php/chat?locale=es

EXTRA: I'm using MiBew in Spanish.

**Comment by faf** [comment]
Frankly I don't get it.

0. What version of Mibew Messenger you're using?
1. What are you doing?
2. What do you expect to see?
3. What do you actually see?

**Comment by faf** [comment]
Closed due to lack of feedback.
