### ISSUE TITLE
Feature Request: Bigger close buttons

### ISSUE THREAD

**Issue by PeaceDealer** [Mibew/mibew#144]
Could we somehow get a bigger more clear close button on the client chat?

Possibly something next to the Send button (same size and everything), but to close the chat.

**Comment by JustBlackBird** [comment]
As far as I know Mibew community (at least its active part) lacks of designers. So I just don't know how this button should looks like.

Also you can create a custom theme with any modifications you want. You could do so without modifications of the core.

**Comment by MichaelTunnell** [comment]
I will be creating a new design for Admin, Client Chat, and Invitations as soon as possible. The admin design is almost ready for testing so I will be submitting a pull request for it this weekend. I'll add this as one of the first improvements I make to the client chat design.

**Comment by faf** [comment]
Implemented with [the plugin](https://github.com/Mibew/big-close-button-plugin).
