### ISSUE TITLE
updated dependencies break mibew

### ISSUE THREAD

**Issue by millerthegorilla** [Mibew/mibew#148]
Hi, I updated the dependencies of mibew by updating the versions of the required libraries in the bower.json file, and then ran bower update.  I then removed lodash and reinstalled version 3.10.1 (the last revision of the 3.0 branch) before running 'gulp default'.  The resulting code installed ok, and the back end is fine, but when I call the client, the iframe is constructed with round corners but no visible content.
This might be a support request, since perhaps I have made a mistake, so I will post this in the forum as well, but may I request that the team update the dependencies please?

**Comment by JustBlackBird** [comment]
I've already answered you at the forum ([here](https://mibew.org/forums/index.php/topic,191981.0.html)).

The point is, you don't need to update dependencies if everything works fine. Normally, we'll update dependencies at the next major (or minor, depending on dependency) release.

If something is broken, it's better to open an issue about the problem.
