### ISSUE TITLE
Thread revision is frequently unnecessarily incremented

### ISSUE THREAD

**Issue by alberto234** [Mibew/mibew#149]
The thread revision is unnecessarily updated in Thread::closeOldThreads().

In this method all threads that are older than some threshold are queried and closed. The issue here is that the call to Thread::nextRevision() occurs even if there are no threads to close. nextRevision() increments the thread revision counter.

The bigger issue is that Thread::closeOldThreads() is called by UsersProcessor::apiUpdate(), and this happens on the "Operator's console refresh time", which by default is 2 seconds. So when the operator has their visitors waiting window open, every two seconds the revision counter is incremented. If there are 10 of the visitors waiting windows open, this will mean every 2 seconds the thread revision is incremented by 10.

The fix for this issue would be to wrap that code block with "if (count($rows) > 0)". For example

Current code

```
        // Perform the cleaning
        $revision = self::nextRevision();
        foreach ($rows as $row) {
            $thread = Thread::createFromDbInfo($row);
            $thread->lastRevision = $revision;
            $thread->modified = $now;
            $thread->closed = $now;
            $thread->state = self::STATE_CLOSED;
            $thread->save();
            unset($thread);
        }
```

Code with fix:

```
        if (count($rows) > 0) {
            // Perform the cleaning
            $revision = self::nextRevision();
            foreach ($rows as $row) {
                $thread = Thread::createFromDbInfo($row);
                $thread->lastRevision = $revision;
                $thread->modified = $now;
                $thread->closed = $now;
                $thread->state = self::STATE_CLOSED;
                $thread->save(false);
                unset($thread);
            }
        }
```

Notice that for $thread-save() we are passing in false into the update_revision parameter

Prerequisites
- Set Thread lifetime to a number greater than 0 (600 by default)
- Set the Operator's console refresh time to something small (2 seconds by default)

Issue found in Mibew 2.1.0

**Comment by alberto234** [comment]
I became curious about the thread revision because in my installation I have seen the thread revision get to 1 million. In my installation there are two operators utilizing the system at a maximum of 3 devices each. I can imagine that the thread revision count will soar on installations where there are multiple operators waiting for visitors.

The database field for thread revision is int(11) which represents a 32-bit number. If this is not addressed soon many installations out there may experience an overflow. 

Eyong Nsoesie

**Comment by JustBlackBird** [comment]
Well, it seems that you're right and there is unnecessary revision increment on threads closing.

> The fix for this issue would be to wrap that code block with "if (count($rows) > 0)".

It seems, that extra if there do fix the problem. Also `$thread->save();` should be `$thread->save(false);`. It's a bug.

The main idea here is to make all closed threads have the same revision and actual last modification time.

As for database field, we could use `UNSIGNED INT` for `lrevision` field. Though, I don't think it will work fine on 32-bit processors after the value becomes greater than `2147483647`, because there is no such thing as `unsigned int` in PHP.

**Comment by alberto234** [comment]
> As for database field, we could use UNSIGNED INT for lrevision field. 

Once we are incrementing the thread revision only when there are threads to close, I don't think we will still have the issue of the counter growing too fast. A signed 32-bit integer would suffice for the life time of the installation. Threads do not change state that often.
