### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by luisfserra** [Mibew/mibew#150]
I installed the Mibew and all the requirements during the instalation are ok.

but when I go to login page and "Internal Server Error" :(

You can check the details from server at http://www.ada-legal.com/mibew/teste.php

Can you tell me why?

Thanks in advantage.

**Comment by JustBlackBird** [comment]
Check Apache's error logs. Most likely the problem has nothing with Mibew itself but related with misconfigured server environment.

**Comment by luisfserra** [comment]
The server don't return any error.

**Comment by JustBlackBird** [comment]
It can _return_ nothing but it should _write_ errors to error log. If not, check PHP's configuration (namely [error_reporting](http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting) option).

**Comment by luisfserra** [comment]
sorry, I have request it from hosting and check this attached. Can you see please?
And about the settings this enough: www.ada-legal.com/mibew/teste.php

[log.txt](https://github.com/Mibew/mibew/files/119030/log.txt)

**Comment by JustBlackBird** [comment]
The file, you've attached is IIS access log but Mibew works only with Apache. We don't test Mibew with IIS and don't plan to do so.

**Comment by luisfserra** [comment]
Ok! :( Thanks
