### ISSUE TITLE
Username changing edit out_of_spaced when #chat-header is changed

### ISSUE THREAD

**Issue by Magvegva** [Mibew/mibew#152]
Hi!
When I tried  to make chat window more smaller and changed #chat-header width   to 280px in chat.css the change_visitor_name editor is  falling down and it can't get the user input focus. The only way to do this is to press "TAB" until the focus's there.
[screenshot](http://fes.org.ua/screens/mibew_issue_user_name-change.PNG)
Is there any ideas how to make design more flexible?
Also, I think that make Mibew design customization more flexible - is the field to work.

**Comment by nav666** [comment]
I can adapt the design to you, but you must to pay for a job.

**Comment by faf** [comment]
Closed due to inactivity.
