### ISSUE TITLE
X button or expand popup window

### ISSUE THREAD

**Issue by nabizade** [Mibew/mibew#153]
Hi, 

I want to use X or _ button on popup window. Client cannot use site when Mibew is opened. 

How I can do it?

**Comment by MichaelTunnell** [comment]
I see how that could be a big problem for mobile visitors.

I did some testing to write a mod for this. I was successfully able to make a hide button that minimized the chat window but ran into a problem of getting the chat to come back afterwards so that will require some more testing.
