### ISSUE TITLE
Chat between operators?

### ISSUE THREAD

**Issue by dsurra** [Mibew/mibew#158]
Hello,
I wonder if it is possible to chats between operators, and if possible how?
There a plugin to do this?
Or if you develop it, you should do?
From already thank you very much and sorry for my English.
Diego

**Comment by JustBlackBird** [comment]
Actually there is no such feature in Mibew. More over we did not play to implement such functionality in 2.x branch.

**Comment by siepkes** [comment]
If you guys ever do implement it; I would like to request the feature to disable it ;-). A lot of companies already have an internal chat system (Mattermost, Slack, etc.) and probably (like me) do not want duplication of such functionality.
