### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jonasrrq** [Mibew/mibew#162]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator to inform of the time the error occurred and of anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by faf** [comment]
And what is in your server error log?

**Comment by faf** [comment]
1. Don't create duplicate issues.

2. Error log is not the same as access log.

**Comment by faf** [comment]
@jonasrrq ping

**Comment by faf** [comment]
Closed due to inactivity.
