### ISSUE TITLE
could you please include release zip and tar,gz files in github releases?

### ISSUE THREAD

**Issue by thecotne** [Mibew/mibew#164]

**Comment by faf** [comment]
Do you mean archives with builds that is available at [SourceForge](https://sourceforge.net/projects/mibew/files/core/)?

**Comment by thecotne** [comment]
@faf yes
many projects include change log and builds in github releases 

like atom for example

![screenshot from 2016-06-24 18 15 11](https://cloud.githubusercontent.com/assets/1606993/16340172/a0db59e4-3a37-11e6-98a8-7da85d74fbcc.png)

**Comment by faf** [comment]
And many projects doesn't. :smile: 
Could you please clarify why do you need it?

You see, we're distributing our builds through single CDN to track downloads statistics. But we can miss something important here.

**Comment by thecotne** [comment]
mainly its my personal preference 
i don't like SourceForge and that wait 5 seconds ...

github also can provide statistics also it is very useful when viewing new releases with github
if there is change log and builds and there is list of commits it is just better experience for me

**Comment by faf** [comment]
Ok. I've got your point. And maybe someday we'll really switch to Github for all things related to releases...
