### ISSUE TITLE
operators getting chats from other groups (they are not in!)

### ISSUE THREAD

**Issue by pandiStefo** [Mibew/mibew#166]
We seem to be experiencing operators receiving chats from customers via a group that they are not connected to .

What can I do ?

**Comment by faf** [comment]
To begin with, you can supply information about your environment, and the version of Mibew Messenger you use.

And then you can write step by step:

1. What exactly did you do?
2. What did you expect?
3. What did you actually got?

**Comment by faf** [comment]
@pandiStefo ping

**Comment by pandiStefo** [comment]
I am nor using mibew anymore.Thank you for your response.

**Comment by SomeDevWeb** [comment]
Hi. I am experiencing the same issue and I'd actually like to use mibew, but this is a showstopper too for my case, TBH.
So, I use Mibew 3.6.0
- I enabled "Groups" and "Group isolation"
- I created 2 groups "Company1" and "Company2"
- I created 2 operators assigned each to its respective "company" - "Company1 Operator" and "Company2 Operator"
- Both operators have permission to only "edit their own profile", nothing else.
- I created a button that is ONLY assigned to "Company1" group
- I added the button to a front-end page.
- I log in with the "Company2 Operator"
- Now the little issues appear: on the front-page, the button shows "offline", which is fine, but in the operator2 admin dashboard List of visitors waiting, I can see the guest or user that started the chat with Operator1...

As a thought, the point of this is to have multiple "Companies" or admin users that can see and manage their own settings and operators, but completely independent from the other ones. In other words, a multi-admin feature...
So from what I understood and tried so far, "Groups" can pretty much accomplish that. 
This is the first issue I saw with the desired behaviour. 
Thanks for any help looking into this!

**Comment by SomeDevWeb** [comment]
I'm coming back with updates. It seems like it works actually. It could be a cache or session glitch... 
I logged out of all the operators accounts and cleared all the browsers data, then tried again and this time is as expected: an operator can't see the chats of another one from another group.
