### ISSUE TITLE
Mibew Complete Redesign Contribution

### ISSUE THREAD

**Issue by MichaelTunnell** [Mibew/mibew#177]
A very long time ago I said that I would be redesigning Mibew and while I intended to do so Mibew was not at a state where it was practical for me do so. I eventually got really busy and just neglected to follow up on my promise.

Well today is the day I finally follow up on that promise, so here is the new design concept.

Preview Images:
1. Visuex.com with a new style Start Chat Button - https://i.imgur.com/kP1CaiU.jpg
2. Login Page - https://i.imgur.com/kJ54wJf.jpg
3. Administration Panel - https://i.imgur.com/DKegBac.jpg

YouTube Video Demo:
https://youtu.be/b2WQBjPXZuk

I created a zip file and sent it to you guys in email. I won't be releasing the theme just yet publicly because it is far from done and I don't want to field support questions when I guarantee it's going to have some issues.

Last time it was more conceptual design with not option for deliverables but now due to the handlebars integration I have lots of deliverables. :)

---

Here is the forum thread I made on this topic: https://mibew.org/forums/index.php/topic,192081.0.html

**Comment by faf** [comment]
Closed after two years of inactivity.

One could reopen this in case of any real changes.
