### ISSUE TITLE
Suggestion: Include FontAwesome with Mibew

### ISSUE THREAD

**Issue by MichaelTunnell** [Mibew/mibew#178]
What do you think of adding the FontAwesome stylesheet to the Mibew design? http://fontawesome.io/icons

I am using it for the redesign (issue #177) but it doesn't have to be if preferred not to. The icons are under an [open license](http://fontawesome.io/license/) by the way.

**Comment by faf** [comment]
As far as I can see there are no license-releated troubles with such addition. So, why not? :)

**Comment by MichaelTunnell** [comment]
Fantastic. I will continue to use it in my redesign initiative. :)
