### ISSUE TITLE
Bug: Online/Offline Value in Admin is Inconsistent

### ISSUE THREAD

**Issue by MichaelTunnell** [Mibew/mibew#181]
```
                        {{#if warnOffline}}
                            {{#unless isOnline}}
                                echo offline
                            {{/unless}}
                        {{else}}
                                echo online
                        {{/if}}
```

The above code is used to indicate if an operator is logged in or not but the value it outputs is inconsistent depending on the page parsing it.

On the dashboard:
- If you are not online in the "console" then it displays the offline message.
- If you are online then it will display nothing.

In the console (visitors page):
- If online, displays online properly.
- if offline, well impossible really.

On any other page:
- If online, displays as online.
- If offline, displays as online.

---

This can be tested using my theme where I moved the indicator to the side menu.

**Comment by faf** [comment]
Well, actually the given code should not be used the way you've described. There is a logical mistake. If the appropriate warning is switched off (or not defined), then the operator will be shown as "online" regardless of his actual status.

**Comment by faf** [comment]
At the same time I understand that you want to be able to get an actual status of an operator on any page in the administrative interface.

**Comment by faf** [comment]
Now one could use `is_online` value in the templates for any page of the administrative interface.

**Comment by MichaelTunnell** [comment]
Awesome, so I can modify my theme to use the new is_online call to display it how I intended?

**Comment by MichaelTunnell** [comment]
that's fine . . . I will just put it as a known bug so people can be aware of the issue in the meantime.

**Comment by faf** [comment]
So, it's done, the name will be the same old `isOnline`.

**Comment by MichaelTunnell** [comment]
So I assume I won't need to change the code after all?

**Comment by faf** [comment]
Yep, seems so.

**Comment by MichaelTunnell** [comment]
Nice! ;)
