### ISSUE TITLE
Suddenly Receiving AccessDeniedException

### ISSUE THREAD

**Issue by TaxJohn** [Mibew/mibew#182]
I recently installed Mibew on a sub domain, and everything's been working fine for the past 2 weeks, up until this morning when I randomly started experiencing the below exception:

> [09-Nov-2016 14:21:29 Africa/Johannesburg] PHP Warning:  A request cannot be properly handled because of uncaught exception Mibew\Http\Exception\AccessDeniedException "" (/var/www/chat.website.com/public_html/libs/classes/Mibew/RequestProcessor/ThreadProcessor.php:349) in /var/www/chat.website.com/public_html/libs/classes/Mibew/RequestProcessor/AbstractProcessor.php on line 256

To be clear, clients and agents are able to connect and use the chat, they seem unaffected.

I am honestly quite stumped as to what could be causing this, could I ask someone to please shed some light on it?

Thanks

**Comment by faf** [comment]
You've already asked about the issue [on the forum](https://mibew.org/forums/index.php/topic,192096.msg199449.html). The discussion is out there.

**Comment by shatmanov** [comment]
I got the same error.
It appears when a visitor writes something to the chat.
Also, the visitor does not see the messages, although the operator sees everything.
