### ISSUE TITLE
Question: Differences between pre-built js files and custom built

### ISSUE THREAD

**Issue by nakupanda** [Mibew/mibew#183]
Hi,

Thanks for the great project.

I'm having troubles when compiling js files, see below screenshots

![image](https://cloud.githubusercontent.com/assets/3096286/20665172/6f5242d8-b599-11e6-8d6d-9575a6892335.png)

Red lines are pre-built version while greens are those generated after running 'gulp js' locally, the differences apparently have led a problem:

![image](https://cloud.githubusercontent.com/assets/3096286/20665218/ae723720-b599-11e6-9b5f-f20aaefee075.png)

Any clue to solve this problem? Thanks.

**Comment by nakupanda** [comment]
Have checked gulpfile.js and found below ordered files

var getClientSideApp = function(name) {
    var appSource = config.jsPath + '/source/' + name;

    return gulp.src(appSource + '/**/*.js')
        .pipe(order(
            [
                appSource + '/init.js',
                // The following line is equivalent to
                // gulp.src([appSource + '/*.js', '!' + appSource + '/app.js']);
                appSource + '/!(app).js',
                appSource + '/models/**/base*.js',
                appSource + '/models/**/*.js',
                appSource + '/collections/**/base*.js',
                appSource + '/collections/**/*.js',
                appSource + '/model_views/**/base*.js',
                appSource + '/model_views/**/*.js',
                appSource + '/collection_views/**/base*.js',
                appSource + '/collection_views/**/*.js',
                appSource + '/regions/**/base*.js',
                appSource + '/regions/**/*.js',
                appSource + '/layouts/**/base*.js',
                appSource + '/layouts/**/*.js',
                appSource + '/**/base*.js',
                // The following line is equivalent to
                // gulp.src([appSource + '/**/*.js', '!' + appSource + '/app.js']);
                '!' + appSource + '/app.js',
                appSource + '/app.js'
            ],
            {base: process.cwd()}
        ))
        .pipe(concat(name + '_app.js'));
}

Could this be the cause or something else?

**Comment by faf** [comment]
to begin with, have you performed all steps from this [chapter](https://github.com/Mibew/mibew#build-from-sources) before running gulp?

**Comment by nakupanda** [comment]
thanks for replying, Yes I have read it few times, I also have successfully built pages using gulp.

**Comment by faf** [comment]
ok. and what about your environment (i.e. OS, version of node.js, etc.)?

**Comment by nakupanda** [comment]
OS:
Ubuntu Server 14 LTS running in Virtualbox

NodeJS:
v0.10.25

Gulp:
CLI version 3.9.0

If possible, please kindly tell me if you're fine running the project within all js files that built with command 'gulp js' ?

**Comment by faf** [comment]
Very odd. At the time I've been able to successfully compile js using:

1. node.js 0.10.10 and gulp 3.8.11
2. node.js 6.9.2 and gulp 3.8.11
3. node.js 6.9.2 and gulp 3.9.1

What is the version of your local gulp?

**Comment by nakupanda** [comment]
My local gulp is version 3.8.11 and global is 3.9.0, now trying something else.

BTW have you checked all js files that generated after running 'gulp js' are running fine? I have no problem running the command but when using Mibew via browser due to the file order problem.

**Comment by faf** [comment]
of course, I've tested everything after the compilation.

you could try to level up the version of your local gulp and try again. update your local repo and run `npm install`. (i presume) it will update your local gulp up to 3.9.1. then you can also update your global gulp.

**Comment by nakupanda** [comment]
Thanks for your help. I try placing a new copy somewhere else and installed new npm packages and ran the command again it worked perfectly.

Please close the issue :)
