### ISSUE TITLE
Mibew generates absolute URLs even when they are not really needed.

### ISSUE THREAD

**Issue by JustBlackBird** [Mibew/mibew#187]
I've installed Mibew on a virtual machine with apache on port `80` (default HTTP port). Also I have nginx that is installed on another virtual machine on port `8080` and proxy all the requests to Mibew. I expect Mibew to generate only "Absolute Path" URLs (like `/mibew/operator/`), so I can serve all the pages with nginx without thinking about host/port inconsistency.

The problem is Mibew generates "Absolute URLs" (like `http://localhost/mibew/operator`) even when they are not really needed. In such case real Mibew's host/port are visible from the outside and are not served by nginx.

It seems that the current implementation of [UrlGenerator](https://github.com/Mibew/mibew/blob/master/src/mibew/libs/classes/Mibew/Routing/Generator/UrlGenerator.php) is smart enough to generate "Absolute URLs" when it has to (even if the generator was asked about different type of URL). So why the developers decided to generate "Absolute URLs" manually?

Here is the list of problem places (it's not completed 'cause I'm still facing problems from time to time):

- [`\Mibew\Controller\Chat\StyleController::loadPopupStyleAction`](https://github.com/Mibew/mibew/blob/master/src/mibew/libs/classes/Mibew/Controller/Chat/StyleController.php#L53)

**Comment by playcraft1** [comment]
This issue might be related to #188

**Comment by faf** [comment]
We need confirmation that #194 has fixed this.

**Comment by faf** [comment]
More than two months passed, no complaints were reported. Let's presume that the issue is fixed, but one could reopen in the future if the original problem is still persists.
