### ISSUE TITLE
How to use built-in update tool?

### ISSUE THREAD

**Issue by everyx** [Mibew/mibew#189]
I just follow this document in Mibew sIte: [Installation and update](https://docs.mibew.org/installation-and-update.html), and when I backup, unzip new file then restore files and correct all rights, I visit http://<yourdomain>/mibew/update/ and I got this error:

> Query failed: Unknown column 'initialized' in 'field list'

and I found that:

> Mibew starting from 2.0.0-beta.1 version can be updated to later versions using built-in update tool.

so how can I update 2.1.2 to ~~2.1.2~~2.2.0 using **built-in update tool**? I can't find the tool in the dashboard.

**Comment by faf** [comment]
To begin with, what version of Mibew Messenger are you trying to update?

(And BTW, the actual version of Mibew Messenger is 2.2.0.)

**Comment by everyx** [comment]
@faf Sorry about the wrong description above, I just correct it. My current version is 2.1.2 and I want to update 2.2.0. thanks

**Comment by snewell92** [comment]
Have you navigated to **https://blinky.charmsoffice.com/mibew/index.php/operator/about** and clicked the "*Check for available updates*" link?

**Comment by snewell92** [comment]
Well actually, maybe disregard my comment. It seems you tried to manually update and are now getting an error, correct? I think the built-in update tool is on that about page (correct me if I'm wrong). That error is probably related to something else, possibly a migration the built in tool may have done for you, but now your database doesn't?

**Comment by everyx** [comment]
Yes, I found the link and it works correctly, but I can't find some way to
click and upgrade automatically, so, the build in update tool is just a new
version check tool?

2017年3月3日 下午11:05，"snewell92" <notifications@github.com>写道：

**Comment by snewell92** [comment]
I'll do some digging, I believe a CronJob using that CronKey is what might be needed. The code [here](https://github.com/Mibew/mibew/tree/master/src/mibew/libs/classes/Mibew/Maintenance) seems to have the capacity to apply updates, but maybe it needs to be triggered by that cronjob.

I'll let you know what I find (I remember reading somewhere about how to set up this cronjob...)

**Comment by everyx** [comment]
Maybe the only upgrade way is manually update, I try manually update and
got an error, it's looks like a database problem, but I can't sure
actually. And I found the document said have a built-in upgrade tool, so I
think maybe I can use it to update my current Mibew, but maybe it just a
checking tool.

2017年3月3日 下午11:07，"snewell92" <notifications@github.com>写道：

Well actually, maybe disregard my comment. It seems you tried to manually
update and are now getting an error, correct? I think the built-in update
tool is on that about page (correct me if I'm wrong). That error is
probably related to something else, possibly a migration the built in tool
may have done for you, but now your database doesn't?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Mibew/mibew/issues/189#issuecomment-283977899>, or mute
the thread

**Comment by snewell92** [comment]
I think you did it correctly. You seem to have followed the instructions from the readme.

> UPDATE
> 
> 1. Backup your actual installation (i.e. code and database).
> 2. Delete all items in your Mibew Messenger directory on the server.
> 3. Unpack the archive with the official distrubition in that directory.
> 4. Remove install.php file.
> 5. Restore configuration (configs/ directory), plugins (plugins/ directory),
>    (maybe) custom styles (if you have any), (maybe) additional
>    locales (if you use any), and avatars (files/avatar/ directory) from the
>    backup you've made at the step 1.
> 6. Visit http://<yourdomain>/<path to your Mibew Messenger>/update and follow
>    the instructions to update the database tables (if needed).

That last step says to update the database tables if needed. I wonder how we're supposed to know what to do there? Maybe there's some information somewhere.

**Comment by snewell92** [comment]
I'm not a dev of mibew, just another programmer + server-admin - so maybe wait for a mibew dev to shed some light. Sorry I couldn't be more helpful.

**Comment by everyx** [comment]
> That last step says to update the database tables if needed. I wonder how we're supposed to know what to do there? Maybe there's some information somewhere.

Yes, I can't find how to upgrade my datebase, maybe it should update automally when I visit `<MIBEW-SITE>/update`.

> I'm not a dev of mibew, just another programmer + server-admin - so maybe wait for a mibew dev to shed some light. Sorry I couldn't be more helpful.

Thanks @snewell92 :)

**Comment by faf** [comment]
At the moment Mibew Messenger can check for updates (either manually - if one uses the link 'Check for available updates' on the 'About' page, or automatically - by cron), and upgrade your database if needed (once you've visited `<MIBEW-SITE>/update` page and confirm the upgrade as it is written in documentation).

However, it can not automatically download and apply updates to your code. At least for now.

@everyx , Are you sure you've visited the `<MIBEW-SITE>/update` page and have got the error?

**Comment by everyx** [comment]
@faf Yes, I use SSL over my site, and vist `https://<MIBEW-SITE>/update` got the error bellow:

> Query failed: Unknown column 'initialized' in 'field list'

but the version 2.1.2 is works as expected.

My server environment:

```shell
user@host$ mysql -V
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

user@host$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**Comment by faf** [comment]
@everyx I have one suspicion... Do you have any plugins installed? And if so, could you disable all of them before replacing the code and trying to update the database?

**Comment by everyx** [comment]
@faf Yes, I have installed some plugin, and I'll have a try, thanks :)

**Comment by faf** [comment]
@everyx Please, provide feedback afterwards. It's really important issue.

**Comment by everyx** [comment]
@faf OK, I'll have a try in this sunday and will leave the result in here, thanks :)

**Comment by everyx** [comment]
@faf I just have a test with this follow steps:

1. disable all plugins
2. backup files and database
3. remove all mibew files
4. download and unzip mibew
5. change owner and permission
6. restore all files and data
7. visit /mibew/update and follow the instructions in the page
8. everything is works ok

so, I think we should improve the document, add disable all plugin before update
