### ISSUE TITLE
Only show notification to the owner if a operator is specicated and status is online?

### ISSUE THREAD

**Issue by everyx** [Mibew/mibew#190]
I found that when I specicate my operator_code in a chat link, I can get the notification, but other staff can also get the notification, and just see my name in "Operator" column.

I want only notify me when the operator is specicate to me, so what can I do for this?

**Comment by faf** [comment]
Implemented as a plugin:

* https://github.com/Mibew/filter-visitors-by-operator-code-plugin
* https://mibew.org/plugins#mibew-filter-visitors-by-operator-code
