### ISSUE TITLE
ssl chat window breaks on proxy

### ISSUE THREAD

**Issue by snewell92** [Mibew/mibew#191]
Since mibew should not care if it is behind a proxy or hosted in some convoluted set up, try the following.

I found this on an ubuntu 14.04 with the latest mibew with php7.

- Set up nginx reverse-proxy with ssl encryption (letsencrypt is the CA, shouldn't matter)
- In mibew settings, click on the **allow secure connections** and also the **force chats...** option
- All mibew pages on admin will load correctly (since nginx is doing the ssl, it all works fine)
- Now grab the button code from mibew, and plant that on another page (can be on a local computer).
- Try clicking the button to initiate an iframe chat **error will occur**

There's a weird redirection happening that **strips out the index.php** controller from the url. *changing the setting to not allow secure connections fixed this*. Since I'm running behind nginx, I still get ssl - but this setting is confusing. Since I had ssl enabled I thought I needed this - but it just caused a problem.

Let me know if I did something wrong or this is outside the scope of mibew. Thank you.

**Comment by faf** [comment]
Mibew Messenger is not supposed to know anything about frontend proxies. And all of its internal settings are relevant only to Mibew Messenger itself and its working environment.

In your case the SSL-related settings defines how Mibew Messenger interacts not with an end user (i.e. a visitor of a site), but with a frontend proxy (i.e. nginx). If you don't use SSL to transmit data between the proxy and Mibew, you shouldn't set that settings on.

Let me provide you an example of working installation of Mibew Messenger that works behind nginx just as yours: https://demo2.mibew.org/ ;)

**Comment by faf** [comment]
Reopen. This could be related to #188.

**Comment by snewell92** [comment]
My point is that the setting is confusing. When googling I found #188, but that is counter to apps not needing to know about proxies in the first place. Which is it? Add some sense of proxies or the environment into Mibew or not?

That being said... maybe the confusing part isn't really Mibew's fault - just as it isn't Mibew's domain to know about infrastructure/specific stacks - maybe stacks are just confusing.

I view this as a UX concern for admins. Maybe change the sub-text of ssl "— Please note that your web server should be configured to support https requests." to " -- Only check this if Mibew is interacting directly with end users (not behind a reverse-proxy)"  But maybe that's too specific to this case... I dunno.

**Comment by faf** [comment]
We need confirmation that #194 has fixed this.

**Comment by snewell92** [comment]
Will confirm on 3/15 (Wednesday). This is looking good so I'll close this issue (as I am satisfied), but will reopen if issue persists.

Thanks!!
