### ISSUE TITLE
Popup returns loadStyleSheet callback without https

### ISSUE THREAD

**Issue by snewell92** [Mibew/mibew#192]
The callback **Mibew.Utils.loadStyleSheet** does not respect SSL settings on the settings and returns an http url. This is used to load iframe.css, which will be disallowed on browsers with strict security settings.

The `/chat/style/popup` route should return an appropriately formed URL, so I expected the URL Generator to return an https url when SSL is turned on, but it returned http instead.

Current work around is to hackity hack the popup.js, so that any calls made into loadStyleSheet get checked with this code:

`t=t.substring(0,5)=="https"?t:"https"+t.substring(4);`

before the return statement

Please let me know if I have missed something, thanks for reading!

**Comment by playcraft1** [comment]
If you're running the under the previous said environment (#191), then it's most likely not an issue when #188 is implemented. This is not an issue for me with that fix.

**Comment by snewell92** [comment]
I believe you are correct @playcraft1

**Comment by faf** [comment]
We need confirmation that #194 has fixed this.

**Comment by snewell92** [comment]
Will confirm on 3/15 (Wednesday). This is looking good so I'll close this issue (as I am satisfied), but will reopen if issue persists.

Thanks!!
