### ISSUE TITLE
Get correct user IP when has proxy and adapt for IPv6

### ISSUE THREAD

**Issue by everyx** [Mibew/mibew#198]
When user has proxy and we should get the correct address, and I just send a pull request https://github.com/Mibew/mibew/pull/197 , and when user IP is an IPv6 address, the regular expressions `/(\\d+\\.\\d+\\.\\d+\\.\\d+)/` should adapt for this.

**Comment by faf** [comment]
Fixed by 568e539e49d11145252837f2ddbbaba6c22539a9
