### ISSUE TITLE
Add plugin, or integrate into existing one? Operators Online plugin

### ISSUE THREAD

**Issue by snewell92** [Mibew/mibew#202]
I made [this plugin](https://github.com/snewell92/any-operators-online) a few weeks ago, and I just saw that #174 is landing an official plugin of a related kind (operator status querying).

Could the functionality in my plugin be pulled into that one? Mine's _very_ small, so I don't think it should be added as an official plugin by itself, but mine is useful to me and my team so it might be useful to others.

What do y'all think?

**Comment by everyx** [comment]
Yes, I think we can leave operator code to null and then return is any operator online, and specific operator code then return this operators online status.

**Comment by snewell92** [comment]
Sounds great to me @everyx

**Comment by everyx** [comment]
@snewell92 I just release a new version add your needed feature, but this plugin is direct return `true` or `false` but not JSON object.

Just checkout the [README](https://github.com/everyx/mibew-operator-status-plugin/blob/master/README.md)

**Comment by patmaclondon** [comment]
I've been digging a bit deeper and what I find really odd is that if I click on AWAY, in my admin console it switches to one in MySQL the istatus table, there is however no such thing once you clicked on Available and log out... I have no idea with the coding where it gets there is nobody here from, that would help, I don't want to spend hours and hours tracing and finding what changes when you logout, I just want a simple check nobady online logo red and text offline, someone clicked on available logo blue text online, when they click away, or leave the message page and do maintenance offline

**Comment by patmaclondon** [comment]
I had a thought on this... isn't it more logical to set istatus in MySgl to 0 when you login and to 1 when available, and back to 0 when away or logout? I'm not an expert and you guys now how difficult it is to read someone else's code it takes days to get used to the project, but it's just an idea, which I will play with

**Comment by faf** [comment]
@patmaclondon Please, stop necroposting. You're writing into the issues closed long ago. And your messages are not related to the core project. There is a [separate repo](https://github.com/Mibew/mibew-operator-status-plugin/) for the Operator status plugin.

**Comment by patmaclondon** [comment]
Don't need to get rude trying to get the hang of this... don't use github often

**Comment by patmaclondon** [comment]
@faf Where can I post then?
