### ISSUE TITLE
issue in installation

### ISSUE THREAD

**Issue by solmaz90** [Mibew/mibew#208]
Hi every one
I have uploaded all mibew contains in this route: c://xampp/htdocs/mibew, and there is a file named install.php. for installing I browse this URL="localhost/mibew/install but I get this error:
"Warning: require_once(C:\xampp\htdocs\mibew/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\mibew\libs\init.php on line 26

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\mibew/vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\mibew\libs\init.php on line 26"

I don't know what is wrong exactly! help me please for fixing
Thanks in advance
Solmaz

**Comment by faf** [comment]
There are two ways to install Mibew Messenger.

1. You can download [the official distribution package](https://mibew.org/download2) and follow the instructions in README.txt file.

2. You can download source code of Mibew Messenger and[ build it from sources](https://github.com/Mibew/mibew#build-from-sources).

**Comment by solmaz90** [comment]
Thanks a lot
I did it and my issue has solved
