### ISSUE TITLE
Are there instructions how to customize the layout?

### ISSUE THREAD

**Issue by lordspace** [Mibew/mibew#211]
it would have been so much better if there was a folder called /themes/ and then have default in it that contained all the templates for chats, invitations, pages etc.

**Comment by faf** [comment]
No, it wouldn't.

Default styles for chats, invitations, and operator interface are located in ```styles/<type of style>/default``` dirs.

And if one need a kind of starting point, well... there is [a post at our forum](https://mibew.org/forums/index.php/topic,191966.msg199029.html#msg199029). Probably one should write a tutorial for this and publish it at [docs.mibew.org](/Mibew/docs.mibew.org). And maybe someday it will happen.

**Comment by faf** [comment]
The theming guide has been published. https://docs.mibew.org/theming.html
