### ISSUE TITLE
Failed to create tables in Percona

### ISSUE THREAD

**Issue by somlyaip-hl** [Mibew/mibew#218]
### Environment
* Mibew Messenger version: 3.0.0
* OS: debian 8 (docker)
* Web server: apache
* PHP: 5.6
* PHP extensions: many extensions but these are pointless 
* MySQL: Percona XtraDB Cluster
### Expected behavior
Mibew\Maintenance\Installer::createTables() sets revision in revision table, sets dbversion and _instace_id rows in config table.

### Actual behavior
Mibew\Maintenance\Installer::createTables() fails. Especially tables are created but the script fails when try to insert into revision table. dbversion and _instance_id will be not set. 

Precona has a special constraint: all tables must have primary key but revision table doesn't have.
Error message is clearly references to this constraint. But I didn't save it and I solved the problem, so I cannot paste to here the message now.

### Steps to reproduce the behavior
Use a Percona cluster as a database backend and try to run install.php or call manually Mibew\Maintenance\Installer::createTables() method.

Workaround
--
Add a new column into revision table (e.g. SID) as an auto incremented integer primary key. But it can be a problem when try to upgrade database with Mibew's built-in feature. Am I right?

Guys, I know that Percona is not a 'classical' MySQL but many company use cluster solutions to store data. Some other cluster solution will behave the same way because they need primary keys to synchronize tables between nodes. So I think supporting clusters will be great in this project.

**Comment by faf** [comment]
1. `dbversion` and `_instance_id` fields belongs to `config` table which has a primary key. So, I suppose that you meant that installation failed before the table was filled with the appropriate values.

2. The only table without primary key is `revision` indeed. That's a service table acting as an incremental counter with a single value.

3. I believe that you've seen this kind of error:
```
ERROR 1105 (HY000): Percona-XtraDB-Cluster prohibits use of DML command on a table (mibew.revision) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER
```

4. The solution here is to either change the `pxc_strict_mode` parameter in the database configuration, or to add some syntethic primary key to the table. At the moment I'm not sure what path is the right one. Need more time to dig into the issue.

**Comment by faf** [comment]
I don't believe that addition of primary key to `revision` will have any serious impact on performance of the application. So in the upcoming release all tables will have primary keys.

**Comment by somlyaip-hl** [comment]
@faf,
1. Yes. Exactly that happend.
3. Yes, that was the error message.
4. Overwriting `pxc_strict_mode` was not souitable for us because it disables some other constraints which were important for us. 

Thank you for your help and sorry for my late answear.
