### ISSUE TITLE
ipad(apple) safari,where guest click start chat,can not open windows for talk.(ver3.1.0)

### ISSUE THREAD

**Issue by luhongbin** [Mibew/mibew#222]
### Environment
* Mibew Messenger version:
* OS:
* Web server:
* PHP:
* PHP extensions:
* MySQL:

**Comment by faf** [comment]
You should provide more information. At the moment there are no enough data to even try to reproduce the issue. BTW, the template for an issue was created intentionally.

**Comment by faf** [comment]
Moreover, I'm pretty sure that Mibew Messenger works on iPads just fine. I've seen iPad users in the logs of our demo server. In the near future I'll test it on real device, but I'm absolutely confident in the result.

**Comment by luhongbin** [comment]
THINK U faf ,RE INSTALL OK,BUT GUEST WINDOWS TALK STYLE NO GOOD.
