### ISSUE TITLE
MOBILE CHAT WINDOWS LIKE THIS

### ISSUE THREAD

**Issue by luhongbin** [Mibew/mibew#223]
I HOPE SOMEBODY CAN DO IT LIKE THIS:https://beta.rumbletalk.net/B4akfG9R/,VERY GOOD
.WEBSITE:https://www.rumbletalk.com/plugins/

**Comment by faf** [comment]
Neither an issue, nor a valid feature request. There are a lot of web chats out there. You are free to use any of them.

Please, stop spamming, or I'll have to block you.
