### ISSUE TITLE
 When opening a consultant, a pop-up window opens on the page and in a new tab

### ISSUE THREAD

**Issue by sssqqqq** [Mibew/mibew#224]
When opening a consultant, a pop-up window opens on the page and in a new tab

This error can be done by clicking on the link http://premiumweb.tk/ and clicking the button (picture) which opens the consultant

Please tell me how to avoid this mistake.

Thank you in advance!

With respect to you and your business, Stanislav

**Comment by sssqqqq** [comment]
I apologize forgot to mention the version of Mibew Messenger 3.1.0

**Comment by faf** [comment]
At the moment I'm unable to reproduce the issue.

What browser do you use? Have you tried a different one?
