### ISSUE TITLE
MibewTray for Windows

### ISSUE THREAD

**Issue by sssqqqq** [Mibew/mibew#225]
Kind you time of day! Prompt please where it is possible to take MibewTray for Windows. MibewTray found under version 1.6. and for version 3.1 I can not find

Mibew Messenger Version 3.1.0

Thank you!

With respect to you and your business, Stanislav

**Comment by faf** [comment]
Let me quote the description of [Mibew Tray project](/Mibew/tray):

> Mibew Tray is a .NET desktop application designed to work with Mibew Messenger
> live support application.
> 
> **Mibew Tray** should be treated as a separate desktop application **tied**
> **to 1.6.x branch of Mibew Messenger by technology as well as by ideology**.

There are no Mibew Tray for actual versions of Mibew Messenger. And we don't plan to develop it.

At the same time the code is available, so everyone is free to work in this direction.
