### ISSUE TITLE
Logo usage

### ISSUE THREAD

**Issue by asham0** [Mibew/mibew#226]
### Environment
* Mibew Messenger version: 3.1.0
* OS: Ubuntu 16.04
* Web server: Apache2
* PHP: 7.0
* PHP extensions:
* MySQL:  5.7

We have loved your application and have installed it on our server so I just want to know that can we use Mibew logo for the AWS Marketplace?

**Comment by faf** [comment]
Well, in short, you can use the logo to show that you provide a custom version of Mibew Messenger as long as you preserve the appropriate copyright notices.

**Comment by asham0** [comment]
So Is it ok if we use your logo with your license?

**Comment by faf** [comment]
The logo is a part of Mibew Messenger. You can use it as long as you comply with [the license](https://github.com/Mibew/mibew/blob/master/src/mibew/LICENSE.txt).

**Comment by asham0** [comment]
Thank you :-)

**Comment by faf** [comment]
You're welcome.
