### ISSUE TITLE
Broadcasting a message to all clients currently connected

### ISSUE THREAD

**Issue by FabianWilms** [Mibew/mibew#228]
I wanted to know if there is an option to broadcast the same message to multiple clients at once. The easiest way would be to send the message to all connected clients. Is this currently possible?

**Comment by faf** [comment]
No, there are no such feature. But one could write a custom plugin for that (add a route, make a special form for the submission of the message, implement a controller).

**Comment by faf** [comment]
I've wrote the plugin. Maybe it will even be useful.

* https://github.com/Mibew/broadcast-plugin
* https://mibew.org/plugins#mibew-broadcast

**Comment by FabianWilms** [comment]
Wow, thank you very much @faf !
It will surely be useful for our use case! :)
