### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by loydjayme25** [Mibew/mibew#229]
Good Day !
i love to work with your project, can i submit my logo design for it ?

**Comment by faf** [comment]
Hi!

Well, we have no problems with our actual logo, but yours could be better, so why not (as long as you agree to contribute your work to the project)? :)

But we have a [special repo](https://github.com/Mibew/design) for all things related to design. Please, make a fork of that project and send a pull request.

**Comment by loydjayme25** [comment]
the simpler , the awesome it is. how do you find it sir @faf  ?

![mibew](https://user-images.githubusercontent.com/37318022/41079484-87c6f860-6a54-11e8-9a74-b96f9409c57d.png)

**Comment by faf** [comment]
Well, it's completely different from our current logo that was the face of the project for almost five years (and in its turn is based upon the concept of the previous logo). Even the color is different... And I have serious doubts that this logo can be used for icons in small sizes...

So, if you want I can make a vote on our forum for community to decide. But as for myself, sorry, but I'd stay with the old one.

**Comment by loydjayme25** [comment]
i can change the color, and yes please. make a vote in your forum to decide.

**Comment by loydjayme25** [comment]
![mibew](https://user-images.githubusercontent.com/37318022/41142015-c8df10e4-6b26-11e8-905b-c8fff4298fb6.png)

pls have a vote , its my honor to contribute to your project.

**Comment by loydjayme25** [comment]
@faf good day, i have updated the color.

**Comment by faf** [comment]
Ok, I've made the voting: https://mibew.org/forums/index.php/topic,192220.0.html

But don't expect too much activity. Our community is a little bit dormant. ;)

**Comment by loydjayme25** [comment]
i will respect on what will be the outcome of the voting.

**Comment by loydjayme25** [comment]
@faf  how was the voting sir ?

**Comment by loydjayme25** [comment]
okay @faf  , if you need my design. I can send you anytime :)

**Comment by faf** [comment]
Sad to postulate this, but nobody showed any interest in new logo. So, Mibew Messenger stays with the old one.
