### ISSUE TITLE
HTTP Error 403 - Forbidden

### ISSUE THREAD

**Issue by mercadeosyh** [Mibew/mibew#236]
The Web server is configured to not list the contents of this directory or you do not have enough permissions to access the resource  Error. Page cannot be displayed. Please contact your service provider for more details. (17)

**Comment by faf** [comment]
1. If you're opening an issue you should fill the template.
2. Obviously, you have misconfigured web server. You've even provided the error message. Look into the error log and fix the error. Or find someone who will do it for you.

To sum it up. I'm closing this issue. If you have any additional information on the issue and believe that it's a bug of Mibew Messenger feel free to reopen it.

**Comment by mercadeosyh** [comment]
Estoy usando el tema Unik Versión: 5.
Tengo la ultima version de wordpress, ya desistale y volví a instalar el plugin y nada que funciona. intente instalar una version del plugin que encontre en la pagina creadora y wordpress no me permitio instalarlo. no es problema del web server es problema del plugin pero no se que mas hacer

**Comment by faf** [comment]
What makes you think I'm speaking Spanish? Write in English.

This is **Mibew Messenger** project. It has nothing to do with Wordpress CMS. Moreover, Mibew team has no official plugin for Wordpress at all.
