### ISSUE TITLE
Custom style open only on first visit, on subpage or after refresh

### ISSUE THREAD

**Issue by bocceli** [Mibew/mibew#238]
### Environment
* Mibew Messenger version: 3.2.0
* OS: Win10
* Web server: apache
* PHP: 7.0
* PHP extensions: all required
* MySQL: 5.7.19
### Expected behavior
Mibew chat should always render chosen style
### Actual behavior
Custom style render only on first open, on subpage or after refresh Mibew is rendering wrong (default) style.
### Steps to reproduce the behavior
Render button with custom style, global style left default, open chat in iframe, refresh page or go to subpage.

### Possible way to fix: 
After first init of chat, iframe windows gets url from cookie. Everything would work perfect, if url saved to cookie 'mibew-chat-frame-anyId' contains 'style' parameter.

**Comment by bocceli** [comment]
I did not test that, but with language ('lang' parameter) may this problem occur too.

**Comment by faf** [comment]
No, detection of the locale works in a different way.

But I've just checked it anyway. ;)

**Comment by bocceli** [comment]
Ok, thank you for your FTL fix :)
