### ISSUE TITLE
Non-localizable strings

### ISSUE THREAD

**Issue by tilkov** [Mibew/mibew#240]
### Environment
* Mibew Messenger version: 3.2.1
* OS: Ubuntu 16.04 LTS
* Web server: Nginx 1.10.2g with [this config](https://mibew.org/forums/index.php/topic,192118.msg199541.html#msg199541) and SSL
* PHP: 7.0.32-0ubuntu0.16.04.1
* PHP extensions: PDO/7.0.32-0ubuntu0.16.04.1 pdo_mysql/7.0.32-0ubuntu0.16.04.1 gd/7.0.32-0ubuntu0.16.04.1 curl/7.0.32-0ubuntu0.16.04.1 mbstring/7.0.32-0ubuntu0.16.04.1 
* MySQL: 14.14 Distrib 5.7.24

### Expected behavior
When switching the language of Mibew, all translated strings should work.

### Actual behavior
On **Visitors** and on the client chat the localized text is still in English. I have three languages installed, besides English: **bg**, **ro** and **el**. The strings in question are translated in all of them, but are not used.
Here are the non-localizable strings in the following screenshots:
![screenshot_20190116_083926](https://user-images.githubusercontent.com/546928/51231546-8e88c080-196c-11e9-93ac-a9090e27bfa7.png)
![screenshot_20190116_084008](https://user-images.githubusercontent.com/546928/51231552-921c4780-196c-11e9-84fd-b04864d25cb4.png)
![screenshot_20190116_084142](https://user-images.githubusercontent.com/546928/51231555-93e60b00-196c-11e9-9c0e-48aaa5213cab.png)

### Steps to reproduce the behavior
Switch Language, The above items remain in English.

**Comment by faf** [comment]
As far as I understand all non-translated values comes from the client-side part of Mibew. That part gets localized strings from `/locales/XX/translation.js` where XX stands for two-lettered code of a locale.

So, let's start with the simpliest test. Just manually open the aforementioned file for any locale in question in your Mibew installation. What will you get?

**Comment by tilkov** [comment]
Hi,

I don't have that file in any translation, even in English.
In every /locales/XX/ i have:

**button**  canned_messages.yml  config.yml  mail_templates.yml  translation.po

**Comment by faf** [comment]
Sure, there are no such file in the filesystem. It's generated by Mibew for a browser [on demand](https://github.com/Mibew/mibew/blob/410b925b8dfbd5dd58d9009d895cc23a94963fc0/src/mibew/configs/routing.yml#L121).

By "open" I meant "open in browser".

**Comment by tilkov** [comment]
It must be the Nginx config then.

I just found you explaining it [here](https://mibew.org/forums/index.php/topic,191725.msg198602.html)

Thank you for pointing me at the right direction.

If possible, please include example nginx config in the documentation.

**Comment by faf** [comment]
Yeah, now I remember, there were a number of issues related to nginx and client-side translation back then in 2015. :)

As of documentation... I'll think about it.
