### ISSUE TITLE
Which group missed their chats?

### ISSUE THREAD

**Issue by tilkov** [Mibew/mibew#242]
### Environment
* Mibew Messenger version: 3.2.1
PHP 7.0.32-0ubuntu0.16.04.1 PDO/7.0.32-0ubuntu0.16.04.1 pdo_mysql/7.0.32-0ubuntu0.16.04.1 gd/7.0.32-0ubuntu0.16.04.1 curl/7.0.32-0ubuntu0.16.04.1 mbstring/7.0.32-0ubuntu0.16.04.1 

Is there a way to see more statistics about the missed chats? List of them, and which group missed them are important.

Regards,
Todor

**Comment by faf** [comment]
Probably it can be calculated from the information in database. One could write own plugin (to implement a cron job to calculate the desired statistics and a custom page to display it) or a stand alone script to do the job.

The basic code for statistics that can be used as a starting point is available [here](https://github.com/Mibew/mibew/blob/master/src/mibew/libs/statistics.php).
