### ISSUE TITLE
Improve the login user endpoint

### ISSUE THREAD

**Issue by kelsonthony** [Mibew/mibew#251]
An idea from an ordinary Mibew Chat user
In the next versions, the user could join the chat service to include his name (mandatorily) and optionally have a field for inclusion of the email as well, with the following text below the field "inform your email so that eventually we can resume the contact if necessary "

Currently the "visitor" enters without even entering his name, he enters as a "visitor", and if the connection goes down, there is a discrepancy in the information passed on and the attendant needs to resume this contact later, he will not be able to do this, as he does not have any data from the Visitor.

**Comment by faf** [comment]
There is already pre-chat survey feature, that could be activated here:

Settings -> Optional Services -> Enable "Pre-chat survey"
