### ISSUE TITLE
Query failed: Table 'mibew.plugin' doesn't exist

### ISSUE THREAD

**Issue by Hoerli1337** [Mibew/mibew#253]
### Environment
* Mibew Messenger version: 3.3.1
* OS: Ubuntu 18.04.5 LTS
* Web server: nginx
* PHP: php7.4 / php8.0
* PHP extensions: bcmath, calendar, Core, ctype, curl, date, dom, enchant, exif, FFI, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcntl, pcre, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, pspell, readline, Reflection, session, shmop, SimpleXML, soap, sockets, sodium, SPL, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, Zend OPcache, zip, zlib
* MySQL: 5.7.33-0ubuntu0.18.04.1
### Expected behavior
See the installer

### Actual behavior
Query failed: Table 'mibew.plugin' doesn't exist

### Steps to reproduce the behavior
Download the zip-File or create a own zip-file with the guid on github.

**Comment by faf** [comment]
Are you sure that you followed the installation instruction and requested  ```http://<yourdomain>/mibew/install``` and not  just ```http://<yourdomain>/mibew```?

**Comment by Hoerli1337** [comment]
Yes I followed the instructions.
Whether I unpack the whole thing into the main directory mydomain.com/install or into a subfolder mydomain.com/mibew/install makes no difference.
Both times it does not work.
Does it help anything if I post the nginx config once?

**Comment by faf** [comment]
> Does it help anything if I post the nginx config once?

It depends. However, the more information, the better.

BTW, nginx is a frontend. What's used as a backend? Apache, PHP with FPM, or something more exotic?

**Comment by Hoerli1337** [comment]
Here is my nginx-config:
```
server {
	listen 80;
	listen [::]:80;
	server_name chat.mydomain.com;
	# enforce https
	return 301 https://$server_name$request_uri;
	access_log  /var/log/nginx/chat.access.log;
	error_log   /var/log/nginx/chat.error.log;

	}
 
server {
	listen 443 ssl;
	listen [::]:443 ssl;
 
	root /var/www/chat;
 
	index index.php index.html index.htm;
 
	server_name chat.mydomain.com;
	client_max_body_size 100M;
 
	location / {
		try_files $uri $uri/ /index.php?$args;
	}
 
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		include fastcgi_params;
	}
    ssl_certificate /etc/ssl/nginx/my-cert.crt;
    ssl_certificate_key /etc/ssl/nginx/my-key.rsa;

    access_log  /var/log/nginx/chat.access.log;
    error_log   /var/log/nginx/chat.error.log;
}
```

I use php-fpm. Nothing special and no strange configuration.

**Comment by faf** [comment]
To begin with, Mibew Messenger doesn't officially support PHP in FastCGI mode as a backend. ;)

As far as I can see, your configuration doesn't identical to directives in [```.htaccess```](https://github.com/Mibew/mibew/blob/master/src/mibew/.htaccess) of the project. You throw all incoming requests to ```index.php```, which is wrong, because requests to paths starting with ```/install``` [should be handled by ```install.php```](https://github.com/Mibew/mibew/blob/4f3d0a57f9011709562aa522d16a51ea74078f08/src/mibew/.htaccess#L39).

There was an unofficial example of valid nginx configuration for php-fpm as a backend on our forum [here](https://mibew.org/forums/index.php/topic,192118.msg199541.html#msg199541).

**Comment by Hoerli1337** [comment]
Okay have Apache2 now installed with php7.4-fpm and nginx as proxy. The installation was at least now successful.
Too bad that nginx does not work directly.

**Comment by faf** [comment]
Nope. nginx behaves just as you told him to. The problem was in your configuration. And I've provided you the link to the (probably) correct one.
