### ISSUE TITLE
Cron breaks when "Check updates automatically" is activated

### ISSUE THREAD

**Issue by tzeumer** [Mibew/mibew#256]
### Environment
* Mibew Messenger version: 3.4
* OS: Ubuntu 18
* Web server: Apache
* PHP: 7.4.3
* PHP extensions:
* MySQL: 10.3.25-MariaDB-
### Expected behavior
Cron(s) run with success message (`/mibew/cron?cron_key=123`) when "Check updates automatically" option is checked `mibew/operator/settings/features`.

### Actual behavior
Cron fails and apache error log has entry like `PHP Warning:  Cron job failed. Here are the errors:\n    cURL error (#35): error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type\n in /var/www/html/mibew/libs/classes/Mibew/Controller/CronController.php on line 66, referer: https://localhost/mibew/operator/statistics`. 

Something seems to be wrong with update URL in https://github.com/Mibew/mibew/blob/0317979c9274fc4822c19f393c910a7d7f30bfc4/src/mibew/libs/classes/Mibew/Maintenance/UpdateChecker.php#L78

### Steps to reproduce the behavior
Try with and without "Check updates automatically" option enabled.

**Comment by faf** [comment]
It's about server itself (and it's signature), not about some specifc URL.

What version of openssl do you use? I'm almost sure that it's ```1.1.1f```, but its need to be clarified.

In short, this Summer we plan some low level updates to our infrastructure. However that should be done as gentle as it could be to avoid interruption of services we provide. So at the moment it's just not possible.

The quick fix for the issue in question is to replace the stock ```Mibew\Maintenance\UpdateChecker``` class with the one below:

https://github.com/Mibew/mibew/blob/issue256/src/mibew/libs/classes/Mibew/Maintenance/UpdateChecker.php

Though, I'll leave this issue opened for now.

**Comment by tzeumer** [comment]
Thanks for the quick reply. Yes, it is 1.1.1f (and Ubuntu 20.04.2 LTS - I erroneously wrote "18").

It really is no big issue for me. It's only that I checked the (cron) link in the statistic page and it took me a moment (or two) to figure out that the update check option was the reason an error was displayed. Primarily I was testing the Mibew:PurgeHistory plugin an think this was keeping this second job from working, too. 

I was just a little bit confused, but everything works well now.

**Comment by faf** [comment]
@tzeumer We've managed to upgrade the related part of our infrastructure, so now everything should work just fine. Feel free to reopen the issue in case the problem still persists.
