### ISSUE TITLE
Visitor with multiple tabs open spams staff side of chat with new location messages

### ISSUE THREAD

**Issue by tzeumer** [Mibew/mibew#257]
(I hope it's not a duplicate, but the forum search didn't let me pass the "I'm no robot" check)

### Environment
* Mibew Messenger version: 3.4.1
* OS: Ubuntu 18
* Web server: Apache
* PHP: 7.4.3
* PHP extensions:
* MySQL: 10.3.25-MariaDB-

### Expected behavior & Steps to reproduce the behavior
Settings: button uses full url with https. And (important maybe) the button forces a new browser window.

1. Visitor has multiple tabs with the integrated mibew chat button open (different pages, but same ChatPopups['code'], because used in aside of a content management system)
2. The visitor opens a chat in one tab 
3. Someone from the service staff answers
4. The staff window should only display the current site the user is on

### Actual behavior
For each tab the staff window receives a never ending stream of "Visitor changed to http..." like:

![image](https://user-images.githubusercontent.com/119825/119682516-3c60df80-be43-11eb-9864-37f7a9f14d19.png)

### Question 
Is there some way to disable this behavior or suppress this message? 

Thanks in advance

**Comment by tzeumer** [comment]
I'm generating a random id on each page load (like `$mibew_id = uniqid() . dechex(rand(0, pow(2, 12))); `) to be used in the button code now. I think that should do the trick. Or would there be a better solution :)

**Comment by faf** [comment]
Well, it's not a bug. For Mibew it's just impossible to tell apart a visitor navigating between pages and a visitor switching between tabs. Technically that behaviour almost identical.

However, if you'll be able to figure out the way to do so, probably it would be possible to make a plugin that alters messages usuing [```\Mibew\EventDispatcher\Events::THREAD_GET_MESSAGES_ALTER``` event](https://docs.mibew.org/development/server-side-events.html#thread-events). In theory. ;))
