### ISSUE TITLE
Mattermost plugin

### ISSUE THREAD

**Issue by tzeumer** [Mibew/mibew#260]
A while ago I copied the Slack Plugin and made it work with Mattermost. Now it's just a simpler version that only uses curl and has no other dependencies.

We currently use it as an extra notification layer, but maybe will drop it as the toast and sound notification might very well be sufficient already. 

Before forgetting about it completely, I first wanted to ask, if you'd be be interested in putting it in your plugin list/repository. The README.md and the Plugin.php can be downloaded here (feel free to adjust the copyright header): http://attach.verweisungsform.de/github/2021-06/MibewMattermostPlugin.zip

**Comment by faf** [comment]
Hi,

Thanks for the proposal. I see two possible ways:

1. You create a repo, and we specify it as a third party plugin in the list of known plugins on our site. (Though, in that case one should change the vendor name in the namespace of the plugin as it's described in the docs: https://docs.mibew.org/plugins/installation.html )
2. We make this plugin an official one (after some refactoring). But in that case you have to specify an open source license for the code, so we could make use of it.

**Comment by tzeumer** [comment]
I'd be very fine with option 2. I already left the Apache License Note in the Readme. I added the license text too, now. But basically I copied more from your Slack-Plugin than I added myself anyway :)

**Comment by faf** [comment]
Ok, great. I'll take care of it in the near future. :)

**Comment by faf** [comment]
The plugin has been released:

- https://github.com/Mibew/mattermost-plugin
- https://mibew.org/plugins#mibew-mattermost
