### ISSUE TITLE
Simple way to improve mobile view

### ISSUE THREAD

**Issue by tzeumer** [Mibew/mibew#267]
If you open the chat in an extra window, it is very small on mobile devices (using the default theme). The easy fix is to edit `styles/chats/default/templates_src/server_side/_layout.handlebars` and insert `<meta name="viewport" content="width=device-width,initial-scale=1">` into the head.

I thought this might be a useful note. Otherwise just ignore and close this ticket :)

**Comment by faf** [comment]
Please correct me if I'm wrong, but it's already in the code since #264 was merged into the master. It will appear in the next release for both default and dark themes.
