### ISSUE TITLE
Better button code

### ISSUE THREAD

**Issue by klodeckl** [Mibew/mibew#268]
When using the button code Users make http requests to the chat even if the chat is not used/opened. And the requests are sent the whole time as long as the webpage is opened and consumes resources. It would be better if requests are only made if the user clicks on the chat button.

**Comment by faf** [comment]
Do you mean Widget - Server interaction (in terms of Mibew architecture, see [docs](https://docs.mibew.org/development/core-architecture.html#widget-server-interaction) for more info)? If so, your suggestion would break a bunch of plugins and one of the crucial features of the application. If you meant something else, please be more specific.

**Comment by klodeckl** [comment]
The “Tracking and inviting” option was disabled, but I still had

<div id="mibew-invitation"></div><script type="text/javascript" src="/chat/js/compiled/widget.js"></script><script type="text/javascript">Mibew.Widget.init({"inviteStyle":"\/chat\/styles\/invitations\/default\/invite.css","requestTimeout":10000,"requestURL":"\/chat\/widget","locale":"en","group":"1","visitorCookieName":"MIBEW_VisitorID"})</script>

in my button code. I think since I deleted that part the requests are gone. Am I right that this is the responsible feature?

**Comment by faf** [comment]
One should re-generated the button and replace old code after disabling the tracking. At the same time any manual changes to the button code are discouraged.

**Comment by klodeckl** [comment]
So a hint for regenerating the button code if this option is changed would be helpful. Normally if a feature is disabled it should not work but it still sends requests if the code is not regenerated, but a non Mibew developer does not know this. Manual code changes were not mentioned in this issue.

**Comment by faf** [comment]
> So a hint for regenerating the button code if this option is changed would be helpful. Normally if a feature is disabled it should not work but it still sends requests if the code is not regenerated, but a non Mibew developer does not know this. 

Yes. And that's the reason why the appropriate hint is displayed on each and every change of any button-related features. See [the screenshot](https://user-images.githubusercontent.com/649011/168141988-6c52e0dd-c0fe-4cf7-a1ef-f372ac6666a1.png). Or sneak a peek [at the template](https://github.com/Mibew/mibew/blob/4f05231b04d0f784ed174637e723d44bb5efe851/src/mibew/styles/pages/default/templates_src/server_side/settings_features.handlebars#L16).

> Manual code changes were not mentioned in this issue.

Er?... And what about the sentence quoted below?

> > I think since I deleted that part the requests are gone.

**Comment by klodeckl** [comment]
Ah, if I click save, Sorry, my fault.
Sure I did the change manual because I did not know that it influences the generated button.
Sorry again.
