### ISSUE TITLE
Composer requires php 8.1.0

### ISSUE THREAD

**Issue by pribis** [Mibew/mibew#269]
### Environment
* Mibew Messenger version: 3.5.6
* OS: Ubuntu 18.04.6 LTS
* Web server: Nginx
* PHP: 7.4.30
* PHP extensions:
* MySQL:  
### Expected behavior
Run mibew update. 

### Actual behavior

Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

### Steps to reproduce the behavior
Delete currently installed mibew (after backing up plugins and any configs).
Browse to https://url_to_mibew/update

**Comment by faf** [comment]
Well, leaving aside the fact that PHP 7.4 is not actively supported and will reach EOL in less than 4 months, I don't get the issue itself.

Why do you expect Mibew Messenger to perform any kind of update after you've deleted Mibew Messenger? And if you really deleted Mibew, you'll obviously get 404 on any requests to it.

Update process for production installations is decribed [here](https://github.com/Mibew/mibew/blob/master/src/mibew/README.txt). So, you're either skipped some steps mentioned there, or trying to do something seems strange to me. One should shed more light on the whole situation.

**Comment by pribis** [comment]
omg. It's been a rough week. Thanks.
