### ISSUE TITLE
Chat alerts not perceivable/accessible

### ISSUE THREAD

**Issue by aachips** [Mibew/mibew#272]
My workplace and department use Mibew chat for Student IT Support. I can't perceive the audio chat alerts when we get someone needing help. There are only audio alerts. It would be helpful if there was a visual alert such as changing browser tab color or displaying an active alert on the screen saying there is a new chat request. Issue that alerts are not accessible (perceivable, robust). Looking to find a working solution because I can't fulfill the requirements of my job as it is right now 

### Environment
* Mibew Messenger version: Browser
* OS: Windows
* Web server: A-B Tech
* PHP: echo script tag for active alert prompt on computer when browser version of mibew webpage alert gets a chat request
* PHP extensions: If there is a third party extension to do this, great!
* MySQL: 
### Expected behavior
Perceivable and Robust (accessible) active alerts for new chat request. Having message notifications occur in more than one way. Having the ability to change settings to enabling or disabling types of active alerts.  

### Actual behavior
Can't perceive alert. No way of knowing if there is a chat request while on another browser tab, or program. I have classes I take that use Adobe programs and I don't have the screen real estate to keep that webpage actively open. 

### Steps to reproduce the behavior
log on to browser version of mibew. connect. do something else on computer while someone else sends chat support requests.

**Comment by faf** [comment]
There are a lot of plugins for that: https://mibew.org/plugins-by-category#notifications
