### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by Doug-sps** [Mibew/mibew#273]
### Environment
* Mibew Messenger version: 3.5.7 (from tar.gz)
* OS: Ubuntu 22.04.2 LTS 
* Web server: Apache 2.4.52
* PHP: 8.1.2
* PHP extensions:  mysqlnd opcache pdo xml apcu calendar ctype curl dom exif ffi fileinfo ftp gd gettext iconv intl mbstring mysqli pdo_dblib pdo_mysql pdo_pgsql pgsql phar posix readline shmop simplexml sockets sysvmsg sysvsem sysvshm tokenizer xmlreader xmlwriter xsl (all referenced via /etc/php)
* MySQL: 8.0.33
### Expected behavior
Installed into a test/dev server (hence the reason for so many extensions enabled) to test out. Created another account and got to a part where it suggested uploading an avatar (something the end users would probably do)

### Actual behavior
got white screen of death when uploading PNG image

### Steps to reproduce the behavior
Try to upload a PNG image as avatar

I dug around in the apache logs and extracted/formatted what it spit out there below:

PHP Fatal error:  Uncaught Error: Call to a member function getClientOriginalExtension() on array in {WEBROOT}/mibew/libs/classes/Mibew/Controller/Operator/AvatarController.php:104
Stack trace:
#0 [internal function]: Mibew\\Controller\\Operator\\AvatarController->submitFormAction()
#1 {WEBROOT}/mibew/libs/classes/Mibew/Application.php(143): call_user_func()
#2 {WEBROOT}/mibew/index.php(71): Mibew\\Application->handleRequest()
#3 {main}
  thrown in {WEBROOT}/mibew/libs/classes/Mibew/Controller/Operator/AvatarController.php on line 104, referer: https://{HOST}/mibew/operator/operator/2/avatar

AvatarController.php:
[...]
    public function submitFormAction(Request $request)
    {
        csrf_check_token($request);

        $operator = $this->getOperator();
        $op_id = $request->attributes->getInt('operator_id');
        $errors = array();

        // Try to load the target operator.
        $op = operator_by_id($op_id);
        if (!$op) {
            throw new NotFoundException('The operator is not found');
        }

        $avatar = $op['vcavatar'];
        $file = $request->files->get('avatarFile');

        if ($file) {
            // Process uploaded file.
            $valid_types = array("gif", "jpg", "png", "tif", "jpeg");

            $ext = $file->getClientOriginalExtension(); //Line 104//

Not sure what to do next. I just grabbed the latest tgz from the download page.
--Doug

**Comment by Doug-sps** [comment]
Does the Bug label mean somebody else was able to reproduce it and it wasn't just me?

**Comment by faf** [comment]
@Doug-sps Seems like I'm able to reproduce the problem. Most probably it's a bug related to one of Symfony components. At the moment there is no need in any feedback, I'm exploring the issue.

**Comment by faf** [comment]
Should be fixed in 3.6.0. Feel free to reopen the issue if it's not.
