### ISSUE TITLE
Composer package

### ISSUE THREAD

**Issue by fdelapena** [Mibew/mibew#85]
Have official prebuilt packages on e.g. packagist for easier maintenance between updates.

**Comment by JustBlackBird** [comment]
I'm not sure what are you talking about.

Mibew cannot be updated using `composer update` CLI command thus I don't think we should publish the whole prebuilt project as a package.

**Comment by fdelapena** [comment]
Publishing the whole prebuilt package is useful when mibew is a php dependency on larger projects with integrated chat support without depending on other package manager or scripts, making project dependency maintenance easier.

**Comment by JustBlackBird** [comment]
Mibew cannot be used in the way you want to. May be it'll be changed one day but I really doubt about that.

You see, the project in the repository should be built before it can be used. It's a bad idea to store compiled files in the repository, so we thrown them away a long time ago. This means that we cannot publish the project from the repository "as is".
